'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NoSplashScreen() As Boolean
            Get
                Return CType(Me("NoSplashScreen"),Boolean)
            End Get
            Set
                Me("NoSplashScreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmptyWorld() As Boolean
            Get
                Return CType(Me("EmptyWorld"),Boolean)
            End Get
            Set
                Me("EmptyWorld") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoPause() As Boolean
            Get
                Return CType(Me("NoPause"),Boolean)
            End Get
            Set
                Me("NoPause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SkipIntro() As Boolean
            Get
                Return CType(Me("SkipIntro"),Boolean)
            End Get
            Set
                Me("SkipIntro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property MaxMem() As Integer
            Get
                Return CType(Me("MaxMem"),Integer)
            End Get
            Set
                Me("MaxMem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property MaxVRAM() As Integer
            Get
                Return CType(Me("MaxVRAM"),Integer)
            End Get
            Set
                Me("MaxVRAM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PresetList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("PresetList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("PresetList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowScriptErrors() As Boolean
            Get
                Return CType(Me("ShowScriptErrors"),Boolean)
            End Get
            Set
                Me("ShowScriptErrors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MaxMemEnabled() As Boolean
            Get
                Return CType(Me("MaxMemEnabled"),Boolean)
            End Get
            Set
                Me("MaxMemEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MaxVRAMEnabled() As Boolean
            Get
                Return CType(Me("MaxVRAMEnabled"),Boolean)
            End Get
            Set
                Me("MaxVRAMEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CPUEnabled() As Boolean
            Get
                Return CType(Me("CPUEnabled"),Boolean)
            End Get
            Set
                Me("CPUEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property CPUCount() As Decimal
            Get
                Return CType(Me("CPUCount"),Decimal)
            End Get
            Set
                Me("CPUCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property A3Path() As String
            Get
                Return CType(Me("A3Path"),String)
            End Get
            Set
                Me("A3Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GroupList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("GroupList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("GroupList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExThreadsEnable() As Boolean
            Get
                Return CType(Me("ExThreadsEnable"),Boolean)
            End Get
            Set
                Me("ExThreadsEnable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property ExThreads() As String
            Get
                Return CType(Me("ExThreads"),String)
            End Get
            Set
                Me("ExThreads") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoLogs() As Boolean
            Get
                Return CType(Me("NoLogs"),Boolean)
            End Get
            Set
                Me("NoLogs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoFilePatching() As Boolean
            Get
                Return CType(Me("NoFilePatching"),Boolean)
            End Get
            Set
                Me("NoFilePatching") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nothing")>  _
        Public Property LaunchAction() As String
            Get
                Return CType(Me("LaunchAction"),String)
            End Get
            Set
                Me("LaunchAction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Windowed() As Boolean
            Get
                Return CType(Me("Windowed"),Boolean)
            End Get
            Set
                Me("Windowed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1000, -1000")>  _
        Public Property FormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("450, 620")>  _
        Public Property Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("450, 380")>  _
        Public Property GroupSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("GroupSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("GroupSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ModLocations() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ModLocations"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ModLocations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("262, 205")>  _
        Public Property FrmModLocationsSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FrmModLocationsSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FrmModLocationsSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentPreset() As String
            Get
                Return CType(Me("CurrentPreset"),String)
            End Get
            Set
                Me("CurrentPreset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomMemoryAllocator() As String
            Get
                Return CType(Me("CustomMemoryAllocator"),String)
            End Get
            Set
                Me("CustomMemoryAllocator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomMemoryAllocatorEnabled() As Boolean
            Get
                Return CType(Me("CustomMemoryAllocatorEnabled"),Boolean)
            End Get
            Set
                Me("CustomMemoryAllocatorEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProfileName() As String
            Get
                Return CType(Me("ProfileName"),String)
            End Get
            Set
                Me("ProfileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ProfileNameEnabled() As Boolean
            Get
                Return CType(Me("ProfileNameEnabled"),Boolean)
            End Get
            Set
                Me("ProfileNameEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RunBattlEye() As Boolean
            Get
                Return CType(Me("RunBattlEye"),Boolean)
            End Get
            Set
                Me("RunBattlEye") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Arma3ModPresetLauncher.My.MySettings
            Get
                Return Global.Arma3ModPresetLauncher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
